### ISSUE TITLE
Add layouted PDF version

### ISSUE THREAD

**Issue by fhemberger** [hashicorp/nomad-cheatsheet#2]
Please add link to the [layouted PDF](https://www.datocms-assets.com/2885/1650045163-kubernetes-to-nomad-cheat-sheet-v2.pdf) from the [blog post](https://www.hashicorp.com/blog/the-kubernetes-to-nomad-cheat-sheet) as release and/or to the Markdown document/GitHub page.

**Comment by Amier3** [comment]
Live on the website and the README 😄 , thanks for pointing this out!
